apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./sdeployment.yaml
- ./gateway.yaml

images:
- name: MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-f1260a3
- name: SHADOW_MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-0df1142
