apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./gateway.yaml
- ./sdeployment.yaml

images:
- name: MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-5e38ad8
- name: SHADOW_MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-5e38ad8
