apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./sdeployment.yaml
- ./gateway.yaml
- ./deployment-secret.yaml

images:
- name: MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-f7311d5
