apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./sdeployment.yaml
- ./gateway.yaml
- ./deployment-secret-sealed.yaml


images:
- name: MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-0cb02b0
- name: SHADOW_MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-0cb02b0
