apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./sdeployment.yaml

images:
- name: MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-be19d66
- name: SHADOW_MODEL_IMAGE
  newName: sasumaki/mnist
  newTag: sha-be19d66

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: model-config
  env: environment.properties
  
vars:
- name: MODEL_URI
  objref: { kind: ConfigMap, name: model_config, apiVersion: v1 }
  fieldref: { fieldpath: data.MODEL_URI }
