apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mnist-model-triton
  namespace: seldon-system
spec:
  protocol: kfserving
  predictors:
  - graph:
      implementation: TRITON_SERVER
      modelUri: s3://aiga-models/mnist-4m59n-4092860028
      envSecretRefName: seldon-init-container-secret
      name: mnist
    name: mnist
    replicas: 1
