name: Release application
on:
  push:

jobs:
  build-publish:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      run: ls -la
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - 
      name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sasumaki/mnist
        tag_with_sha: true
  
  bump-staging-images:
    runs-on: ubuntu-latest
    needs: [build-publish]
    if: contains(github.ref, 'staging')
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Get Git Short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${{ github.sha }} | cut -c1-7)"

    - 
      name: Set up Kustomize
      working-directory: ./manifests
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    -
      name: Set shadow to production
      working-directory: ./manifests
      run: |-
        ./kustomize edit set image SHADOW_MODEL_IMAGE="sasumaki/mnist:sha-${{ steps.slug.outputs.sha7 }}"

    - 
      name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "New shadow PR ${{ steps.slug.outputs.sha7 }}"
 
    - 
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with: 
        branch: main


      