name: "Testing modelioust"
on: [pull_request, push]

jobs:
  test:
    needs: build-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.4.0
      with:
          version: "v0.7.0"
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}

    - name: install istio to cluster
      run: |
        curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.4 sh -
        export PATH="$PATH:/home/runner/work/mnist/mnist/istio-1.7.4/bin"
        istioctl install --set profile=demo

    - name: install seldon to cluster
      run: |
        kubectl create namespace seldon-system
        helm install seldon-core seldon-core-operator \
          --repo https://storage.googleapis.com/seldon-charts \
          --set usageMetrics.enabled=false \
          --set istio.enabled=true \
          --namespace seldon-system
        helm install helm-charts/seldon-core-operator seldon-core-operator

    - 
      name: Set up Kustomize
      working-directory: ./manifests
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    -
      name: Update images
      working-directory: ./manifests
      run: |-
        ./kustomize edit set image MODEL_IMAGE="sasumaki/mnist:sha-${{ steps.slug.outputs.sha7 }}"

    - name: Apply deployment to cluster
      run: |
        kubectl apply -f ./manifests

    - name: watch
      run: |-
        kubectl get deployment -n seldon-system
        kubectl rollout status deploy/mnist-model-mnist-0-mnist
